### ISSUE TITLE
Alias "STEP_RENEW" already defined

### ISSUE THREAD

**Issue by igrikus** [maxhoesel-ansible/ansible-collection-smallstep#316]
When numerous `step renew` systemd services are present, multiple sudoers files are installed with the same alias name. As a result, every command utilizing `sudo` will trigger a warning message:

```
/etc/sudoers.d/99_step-myservice-renew:1:90: Alias "STEP_RENEW" already defined
Cmnd_Alias  STEP_RENEW = /usr/bin/systemctl try-reload-or-restart myservice.service
```

**Comment by maxhoesel** [comment]
Thanks for reporting this issue! This should be fixed with #324
