### ISSUE TITLE
support `password_file` creation for all modules using a `password_file` format

### ISSUE THREAD

**Issue by maxhoesel** [maxhoesel-ansible/ansible-collection-smallstep#352]
In addition to supporting `step-cli`'s `--provisioner-password-file` parameter, it would be great if our modules could automatically generate a temporary password file from a provided password input. That way, users can store their passwords in a vault and pass them directory to the modules, no extra tasks required.

**Comment by eengstrom** [comment]
Yes, please - this would be great...

**Comment by eengstrom** [comment]
Thanks for working on this, Max - really appreciate the effort.
