### ISSUE TITLE
Generate a new certificate from signing a certificate request

### ISSUE THREAD

**Issue by patsevanton** [maxhoesel-ansible/ansible-collection-smallstep#391]
Hello! Thanks for

I search/try "Generate a new certificate from signing a certificate request" as doc https://smallstep.com/docs/step-cli/reference/ca/sign/
But not found.
How do I generate a new certificate by signing a certificate request (use ansible-collection-smallstep)?

**Comment by maxhoesel** [comment]
Hi! There is currently no way to sign a CSR with the CA cert through this collection. Doing so would require adding a  `step_ca_sign` module (or maybe including that functionality in `step_ca_certificate`). Issue #340 already talks about this . Until then, you could work around this by using the `step_ca_token` module to create a token, then use that token to create a certificate.
