### ISSUE TITLE
`step_acme_cert`: Issuing a new certificate needs to stop `step-renew` and start it back up again

### ISSUE THREAD

**Issue by ported-pw** [maxhoesel-ansible/ansible-collection-smallstep#450]
Currently, if the following conditions are met:
- A cert was previously issued via ACME
- The `step-renew` service is running
- On a re-execution of the role, this existing certificate is deemed invalid (in my case, it was because I do not add the root certificate to the trust store, and https://ansible-collection-smallstep.readthedocs.io/en/latest/collections/maxhoesel/smallstep/step_acme_cert_role.html#id3 does not have options to set the trusted root for checking certificate validity)
- The `step-renew` service then tries to renew the cert

the `step-renew` service will renew based on the old cert/keypair _before_ the ACME re-issuance, leading to an invalid key/cert pair.
`step ca renew --daemon` does NOT reload the key file before each renew attempt (and neither the cert, it only keeps in memory the one it last generated itself).

I see the following solutions:
1. stopping `step-renew` in any case when a new cert is issued via ACME and then starting it again
2. not using `step ca renew --daemon` but instead a systemd timer

**Comment by maxhoesel** [comment]
Thanks for the report! I think using a systemd timer would be the best long-term solution (I'm honstely not sure why I didn't pick a timer over the daemon approach in the first place) but until that is implemented I'll be sure to merge your fix!
